### ISSUE TITLE
Не правильная ошибка "Поле "Текст модуля" не заполнено."

### ISSUE THREAD

**Issue by alexeyshumaev** [Bazil1c/acc-check-code#1]
В обработке ПроверкаКода в модуле формы в процедуре ВыполнитьПроверкуКода() нужно строки поменять местами:
Было: 
`
	Если Не ПроверитьЗаполнение() Тогда
		Возврат;
	КонецЕсли; 
	ТекстМодуля = ПолучитьТекстМодуля();
`
Стало: 
`
	ТекстМодуля = ПолучитьТекстМодуля();
	Если Не ПроверитьЗаполнение() Тогда
		Возврат;
	КонецЕсли; 
`

**Comment by VVi3ard** [comment]
#2
